steps:
# Create Chart skeleton
- name: 'debian:stable-slim'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        mkdir -p knative/templates
        mv Chart.yaml ./knative
        mv values.yaml ./knative
        mv knative-cluster-role.yaml ./knative/templates

# Get the Istio manifest
- name: 'gcr.io/cloud-builders/wget'
  args: ['-O', 'knative/templates/istio.yaml', 'https://raw.githubusercontent.com/knative/serving/v0.2.1/third_party/istio-1.0.2/istio.yaml']

# Get the Knative manifest
- name: 'gcr.io/cloud-builders/wget'
  args: ['-O', 'knative/templates/knative.yaml', 'https://github.com/knative/serving/releases/download/v0.2.1/release-no-mon.yaml']

# Templatize the chart
- name: 'debian:stable-slim'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        sed -i 's/{{/{{ "{{" }}/g' knative/templates/knative.yaml
        sed -i 's/example.com/{{ .Values.domain }}/' knative/templates/knative.yaml
        sed -i 's/LoadBalancer/{{ .Values.istioIngressType }}/' knative/templates/istio.yaml

# Initialize Helm without Cluster
- name: 'gcr.io/triggermesh/helm'
  args: ['init', '--client-only']

# Install gcs plugin
- name: 'gcr.io/triggermesh/helm'
  args: ['plugin', 'install', 'https://github.com/viglesiasce/helm-gcs.git']

# Package the chart
- name: 'gcr.io/triggermesh/helm'
  args: ['package', 'knative']

# Create repo directory
- name: 'debian:stable-slim'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        mkdir repo
        mv knative-0.2.1.tgz ./repo

# Generate index
- name: 'gcr.io/triggermesh/helm'
  args: ['repo', 'index', '--url', 'https://storage.googleapis.com/triggermesh-charts', './repo']

# Push index to gcs bucket
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', './repo/index.yaml', 'gs://$PROJECT_ID-charts/index.yaml']

# Push it to gcs bucket
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', './repo/knative-0.2.1.tgz', 'gs://$PROJECT_ID-charts/knative-0.2.1.tgz']

# Build the installer
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/knative-installer:0.2.1', '-f', './installer/Dockerfile', '.']

# Tag and push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/knative-installer:0.2.1']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/knative-installer:0.2.1', 'gcr.io/$PROJECT_ID/knative-installer:0.2']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/knative-installer:0.2']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/knative-installer:0.2.1', 'gcr.io/$PROJECT_ID/knative-installer:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/knative-installer:latest']
